#!/bin/bash
# Firewall rules using iptables
# Alternative to UFW for more granular control
# Upstream source: git+ssh://charlie4284@git.launchpad.net/canonical-is-firewalls
#
# Generated by scripts/sync-from-upstream.sh
# Derived from upstream rules/is/ps7.yaml and rules/is/testing.yaml
#
# Key upstream → demo mappings:
#   ps7/infrastructure subnets    → 10.142.0.0/16 (demo LXD bridge)
#   ps7-egress-proxy (91.189.92.x)→ 10.142.65.2 (squid-proxy LXD VM)
#   ps7/dns                       → 10.142.65.3 (dns-server LXD VM)
#   squid port alias              → tcp/3128 (from defs/ports.yaml)

set -euo pipefail

echo "=== Setting up iptables Firewall Rules for Demo ==="
echo "(reflecting upstream: git+ssh://charlie4284@git.launchpad.net/canonical-is-firewalls)"

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

# Default policies — deny incoming, allow outgoing
# Mirrors upstream default-deny-ingress model
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow SSH — upstream: IS VPN / ps7-infra VPN → ps7/infrastructure: ssh (tcp/22)
iptables -A INPUT -p tcp --dport 22 -j ACCEPT

# Allow HTTP/HTTPS — upstream: IS VPN → ps7/infrastructure: http (tcp/80), https (tcp/443)
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT

# Allow squid (3128) from demo network to proxy VM only
# Upstream: ps7/oam → ps7/egress-proxies: squid (tcp/3128)
# Upstream ps7-egress-proxy IPs: 91.189.92.10, 91.189.92.11, 91.189.92.12
iptables -A INPUT -p tcp -s 10.142.0.0/16 -d 10.142.65.2 --dport 3128 -j ACCEPT

# Allow DNS from demo network to DNS VM
# Upstream: various services → ps7/dns: dns (tcp+udp/53)
iptables -A INPUT -p udp -s 10.142.0.0/16 -d 10.142.65.3 --dport 53 -j ACCEPT
iptables -A INPUT -p tcp -s 10.142.0.0/16 -d 10.142.65.3 --dport 53 -j ACCEPT

# Allow inter-VM traffic — upstream: ps7/oam ↔ ps7/oam: any (inter-AZ)
iptables -A INPUT -s 10.142.0.0/16 -j ACCEPT

# Allow ping — upstream: IS VPN → ps7/infrastructure: ping (icmp/echo-request)
iptables -A INPUT -p icmp -j ACCEPT

iptables -A INPUT -j LOG --log-prefix "iptables-dropped: " --log-level 4

iptables-save > /etc/iptables/rules.v4 2>/dev/null || true

echo "=== iptables rules applied ==="
iptables -L -v
