#!/bin/bash
# Firewall rules for LXD VMs using UFW
# Imitates ps7 network isolation
# Upstream source: git+ssh://charlie4284@git.launchpad.net/canonical-is-firewalls
#
# Generated by scripts/sync-from-upstream.sh
# Derived from upstream rules/is/ps7.yaml and rules/is/testing.yaml
#
# Key upstream → demo mappings:
#   ps7/infrastructure subnets    → 10.142.0.0/16 (demo LXD bridge)
#   ps7-egress-proxy (91.189.92.x)→ 10.142.65.2 (squid-proxy LXD VM)
#   ps7/dns                       → 10.142.65.3 (dns-server LXD VM)
#   ps7/ingress-haproxies         → 10.142.65.4 (ingress-controller LXD VM)
#   squid port alias              → tcp/3128 (from defs/ports.yaml)

set -euo pipefail

echo "=== Setting up Firewall Rules for Demo ==="
echo "(reflecting upstream: git+ssh://charlie4284@git.launchpad.net/canonical-is-firewalls)"

apt-get update -q
apt-get install -y ufw

ufw --force reset

# Default policies — deny incoming, services only reachable via explicit rules
# Upstream: default deny incoming in ps7 NGF rules
ufw default deny incoming
ufw default allow outgoing

# Allow SSH from host (LXD bridge)
# Upstream: IS VPN and ps7-infra VPN → ps7/infrastructure: ssh (tcp/22)
ufw allow in on eth0 to any port 22

# Allow HTTP/HTTPS between VMs
# Upstream: IS VPN → ps7/infrastructure: http (tcp/80), https (tcp/443)
ufw allow 80/tcp
ufw allow 443/tcp

# Allow proxy port (3128) from demo network to proxy VM only
# Upstream: ps7/oam → ps7/egress-proxies: squid (tcp/3128)
# Upstream egress proxy hosts: ps7-egress-proxy = 91.189.92.10, 91.189.92.11, 91.189.92.12
# Demo equivalent: 10.142.65.2 (squid-proxy LXD VM)
ufw allow from 10.142.0.0/16 to 10.142.65.2 port 3128 proto tcp

# Allow DNS from demo network to DNS VM
# Upstream: various services → ps7/dns: dns (tcp+udp/53)
# Demo equivalent: 10.142.65.3 (dns-server LXD VM)
ufw allow from 10.142.0.0/16 to 10.142.65.3 port 53

# Allow inter-VM traffic on demo network
# Upstream: ps7/oam ↔ ps7/oam: any (inter-AZ), ps7 infra inter-node traffic
ufw allow from 10.142.0.0/16

# Allow ping/ICMP
# Upstream: IS VPN → ps7/infrastructure: ping (icmp/echo-request)
ufw allow proto icmp

ufw --force enable

echo "=== Firewall setup complete ==="
ufw status verbose
