#!/bin/bash
# sync-from-upstream.sh
#
# Fetches the upstream firewall and proxy configurations from Launchpad and
# generates demo-local equivalents for the LXD test environment.
#
# Upstream sources:
#   Firewall:  git+ssh://charlie4284@git.launchpad.net/canonical-is-firewalls
#   Proxy ACLs: git+ssh://charlie4284@git.launchpad.net/~charlie4284/canonical-is-internal-proxy-configs
#
# The upstream canonical-is-firewalls repo uses a declarative YAML format for
# Canonical's Next-Generation Firewalls.  The relevant upstream files are:
#   rules/is/ps7.yaml     — firewall rules for the PS7 prodstack
#   rules/is/testing.yaml — tunnel rules between PS5/PS7 network gateways
#   rules/is/squid.yaml   — egress proxy (squid.internal) access rules
#   services/is/ps7.yaml  — PS7 host/subnet definitions
#   defs/hosts.yaml       — shared host definitions (incl. ps7-egress-proxy IPs)
#   defs/ports.yaml       — canonical port aliases (squid=tcp/3128, etc.)
#
# This script:
#   1. Clones both upstream repos (requires ~/.ssh/id_rsa with Launchpad access)
#   2. Extracts the PS7/testing-relevant rules from the firewalls repo
#   3. Writes equivalent UFW rules for the LXD demo network (10.142.0.0/16)
#   4. Writes an equivalent squid.conf for the demo egress proxy

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

FIREWALLS_REPO="git+ssh://charlie4284@git.launchpad.net/canonical-is-firewalls"
PROXY_REPO="git+ssh://charlie4284@git.launchpad.net/~charlie4284/canonical-is-internal-proxy-configs"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

SSH_KEY="${HOME}/.ssh/id_rsa"
GIT_SSH_COMMAND="ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no"
export GIT_SSH_COMMAND

DEMO_NETWORK="10.142.0.0/16"
DEMO_PROXY_IP="10.142.65.2"
DEMO_DNS_IP="10.142.65.3"
DEMO_INGRESS_IP="10.142.65.4"

# ── clone upstream repos ──────────────────────────────────────────────────────

echo "=== Cloning upstream firewall configs ==="
git clone "${FIREWALLS_REPO}" "${WORK_DIR}/canonical-is-firewalls" 2>&1

echo ""
echo "=== Attempting to clone upstream proxy configs ==="
if git clone "${PROXY_REPO}" "${WORK_DIR}/canonical-is-internal-proxy-configs" 2>&1; then
    HAS_PROXY_REPO=true
else
    echo "WARNING: Could not clone proxy configs repo — proxy rules will be based on firewall repo squid rules only."
    HAS_PROXY_REPO=false
fi

# ── extract upstream ps7 / testing rules (informational) ────────────────────

echo ""
echo "=== Upstream PS7 firewall service definitions ==="
echo "(from services/is/ps7.yaml)"
cat "${WORK_DIR}/canonical-is-firewalls/services/is/ps7.yaml"

echo ""
echo "=== Upstream testing tunnel rules ==="
echo "(from rules/is/testing.yaml)"
cat "${WORK_DIR}/canonical-is-firewalls/rules/is/testing.yaml"

echo ""
echo "=== Upstream PS7 firewall rules (summary) ==="
echo "(from rules/is/ps7.yaml)"
grep 'comment:' "${WORK_DIR}/canonical-is-firewalls/rules/is/ps7.yaml"

echo ""
echo "=== Upstream squid egress proxy rules (summary) ==="
echo "(from rules/is/squid.yaml)"
grep 'comment:' "${WORK_DIR}/canonical-is-firewalls/rules/is/squid.yaml"

# ── generate demo UFW rules ───────────────────────────────────────────────────
#
# Mapping from upstream ps7.yaml rules to demo LXD equivalents:
#
#  Upstream rule                              │ Demo equivalent
#  ─────────────────────────────────────────  │ ────────────────────────────────
#  IS VPN → ps7/infrastructure: ssh           │ SSH allowed from 10.142.0.0/16
#  IS VPN → ps7/infrastructure: http, https   │ HTTP/HTTPS allowed within demo net
#  ps7/oam → ps7/egress-proxies: squid(3128)  │ 3128 from 10.142.0.0/16 → proxy VM
#  Any → ps7/dns: dns(53)                     │ DNS(53) from 10.142.0.0/16 → dns VM
#  ps7/oam → ps7/oam: any (inter-AZ)         │ All inter-VM traffic on demo net
#  IS VPN → any: ping                         │ ICMP allowed globally
#
# Upstream egress proxy IPs (ps7-egress-proxy in defs/hosts.yaml):
#   91.189.92.10, 91.189.92.11, 91.189.92.12 (and SNAT: 91.189.92.152)
#   → mapped to demo proxy VM: 10.142.65.2

UFW_OUT="${REPO_ROOT}/firewall/ufw-rules.sh"
cat > "${UFW_OUT}" << SCRIPT
#!/bin/bash
# Firewall rules for LXD VMs using UFW
# Imitates ps7 network isolation
# Upstream source: ${FIREWALLS_REPO}
#
# Generated by scripts/sync-from-upstream.sh
# Derived from upstream rules/is/ps7.yaml and rules/is/testing.yaml
#
# Key upstream → demo mappings:
#   ps7/infrastructure subnets    → 10.142.0.0/16 (demo LXD bridge)
#   ps7-egress-proxy (91.189.92.x)→ ${DEMO_PROXY_IP} (squid-proxy LXD VM)
#   ps7/dns                       → ${DEMO_DNS_IP} (dns-server LXD VM)
#   ps7/ingress-haproxies         → ${DEMO_INGRESS_IP} (ingress-controller LXD VM)
#   squid port alias              → tcp/3128 (from defs/ports.yaml)
#   ssh port alias                → tcp/22
#   http/https aliases            → tcp/80, tcp/443

set -euo pipefail

echo "=== Setting up Firewall Rules for Demo ==="
echo "(reflecting upstream: ${FIREWALLS_REPO})"

apt-get update -q
apt-get install -y ufw

ufw --force reset

# Default policies
# Mirrors upstream: default deny incoming, services only reachable via explicit rules
ufw default deny incoming
ufw default allow outgoing

# Allow SSH from host (LXD bridge)
# Upstream: IS VPN and ps7-infra VPN → ps7/infrastructure: ssh
ufw allow in on eth0 to any port 22

# Allow HTTP/HTTPS between VMs
# Upstream: IS VPN → ps7/infrastructure: http, https
ufw allow 80/tcp
ufw allow 443/tcp

# Allow proxy port (3128) from demo network to proxy VM
# Upstream: ps7/oam → egress-proxies: squid (tcp/3128)
# Upstream egress proxy hosts: ps7-egress-proxy = 91.189.92.10/11/12
# Demo equivalent: 10.142.65.2 (squid-proxy LXD VM)
ufw allow from ${DEMO_NETWORK} to ${DEMO_PROXY_IP} port 3128 proto tcp

# Allow DNS from demo network to DNS VM
# Upstream: various services → ps7/dns: dns (tcp+udp/53)
# Demo equivalent: 10.142.65.3 (dns-server LXD VM)
ufw allow from ${DEMO_NETWORK} to ${DEMO_DNS_IP} port 53

# Allow inter-VM traffic on demo network
# Upstream: ps7/oam ↔ ps7/oam: any (inter-AZ), ps7 infra inter-node traffic
ufw allow from ${DEMO_NETWORK}

# Allow ping/ICMP
# Upstream: IS VPN → ps7/infrastructure: ping (icmp/echo-request)
ufw allow proto icmp

# Allow PS5↔PS7 tunnel establishment
# Upstream: rules/is/testing.yaml — bidirectional any between ps5-nwgw and ps7-nwgw
# (In the demo, both tunnel endpoints are within the same LXD network)
ufw allow from ${DEMO_NETWORK} to ${DEMO_NETWORK}

ufw --force enable

echo "=== Firewall setup complete ==="
ufw status verbose
SCRIPT
chmod +x "${UFW_OUT}"
echo "Written: ${UFW_OUT}"

# ── generate demo iptables rules ─────────────────────────────────────────────

IPTABLES_OUT="${REPO_ROOT}/firewall/iptables-rules.sh"
cat > "${IPTABLES_OUT}" << SCRIPT
#!/bin/bash
# Firewall rules using iptables
# Alternative to UFW for more granular control
# Upstream source: ${FIREWALLS_REPO}
#
# Generated by scripts/sync-from-upstream.sh
# Derived from upstream rules/is/ps7.yaml and rules/is/testing.yaml
#
# Key upstream → demo mappings:
#   ps7/infrastructure subnets    → 10.142.0.0/16 (demo LXD bridge)
#   ps7-egress-proxy (91.189.92.x)→ ${DEMO_PROXY_IP} (squid-proxy LXD VM)
#   ps7/dns                       → ${DEMO_DNS_IP} (dns-server LXD VM)
#   ps7/ingress-haproxies         → ${DEMO_INGRESS_IP} (ingress-controller LXD VM)
#   squid port alias              → tcp/3128 (from defs/ports.yaml)

set -euo pipefail

echo "=== Setting up iptables Firewall Rules for Demo ==="
echo "(reflecting upstream: ${FIREWALLS_REPO})"

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

# Default policies — deny incoming, allow outgoing
# Mirrors upstream default-deny-ingress model
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Allow loopback
iptables -A INPUT -i lo -j ACCEPT

# Allow established/related connections
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow SSH
# Upstream: IS VPN / ps7-infra VPN → ps7/infrastructure: ssh (tcp/22)
iptables -A INPUT -p tcp --dport 22 -j ACCEPT

# Allow HTTP/HTTPS
# Upstream: IS VPN → ps7/infrastructure: http (tcp/80), https (tcp/443)
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT

# Allow squid proxy (3128) from demo network to proxy VM only
# Upstream: ps7/oam → ps7/egress-proxies: squid (tcp/3128)
# Upstream ps7-egress-proxy IPs: 91.189.92.10, 91.189.92.11, 91.189.92.12
# Demo equivalent: ${DEMO_PROXY_IP}
iptables -A INPUT -p tcp -s ${DEMO_NETWORK} -d ${DEMO_PROXY_IP} --dport 3128 -j ACCEPT

# Allow DNS from demo network to DNS VM
# Upstream: various → ps7/dns: dns (tcp+udp/53)
iptables -A INPUT -p udp -s ${DEMO_NETWORK} -d ${DEMO_DNS_IP} --dport 53 -j ACCEPT
iptables -A INPUT -p tcp -s ${DEMO_NETWORK} -d ${DEMO_DNS_IP} --dport 53 -j ACCEPT

# Allow inter-VM traffic on demo network
# Upstream: ps7/oam ↔ ps7/oam: any (inter-AZ)
iptables -A INPUT -s ${DEMO_NETWORK} -j ACCEPT

# Allow ping/ICMP
# Upstream: IS VPN → ps7/infrastructure: ping (icmp/echo-request)
iptables -A INPUT -p icmp -j ACCEPT

# Log dropped packets
iptables -A INPUT -j LOG --log-prefix "iptables-dropped: " --log-level 4

iptables-save > /etc/iptables/rules.v4 2>/dev/null || true

echo "=== iptables rules applied ==="
iptables -L -v
SCRIPT
chmod +x "${IPTABLES_OUT}"
echo "Written: ${IPTABLES_OUT}"

# ── generate demo squid.conf ──────────────────────────────────────────────────
#
# Upstream squid rules (rules/is/squid.yaml) allow outbound:
#   ftp, http, https, matrix-federation, ping
# from squid.internal to any external destination.
#
# Upstream squid.internal access is granted from:
#   rfc1918-10 (10.0.0.0/8), VPN, various internal subnets
#
# Upstream egress proxy IPs: 91.189.92.10/11/12 (ps7-egress-proxy in defs/hosts.yaml)
# Demo equivalent: ${DEMO_PROXY_IP}
#
# Upstream DNS nameservers used by squid: internal DNS → demo equivalent: ${DEMO_DNS_IP}

SQUID_OUT="${REPO_ROOT}/proxy/squid.conf"
cat > "${SQUID_OUT}" << CONF
# Squid proxy configuration for demo environment
# Imitates egress.ps7.internal:3128
# Upstream source: ${PROXY_REPO}
# Firewall rules source: ${FIREWALLS_REPO}
#
# Generated by scripts/sync-from-upstream.sh
#
# Upstream context:
#   The PS7 egress proxies (ps7-egress-proxy: 91.189.92.10/11/12) run Squid
#   and are the sole outbound HTTP/HTTPS path for PS7 instances.
#   Access control is split: the firewall (canonical-is-firewalls) controls
#   which hosts can reach the proxy on tcp/3128; the proxy ACLs (this config,
#   from canonical-is-internal-proxy-configs) control what destinations are
#   allowed through.
#
#   From rules/is/squid.yaml upstream:
#     - squid.internal allows outbound: ftp, http, https, matrix-federation, ping
#     - Access from: rfc1918 10.x, VPN, various internal subnets
#     - Denied by default to all other sources
#
#   Demo mapping:
#     squid.internal         → this VM (${DEMO_PROXY_IP})
#     rfc1918-10 (10.0.0.0/8) → 10.142.0.0/16 (demo LXD network)
#     squid port (tcp/3128)  → http_port 3128 (from defs/ports.yaml)
#     upstream DNS           → ${DEMO_DNS_IP} (dns-server LXD VM)

# Port — matches upstream defs/ports.yaml: squid: [tcp/3128]
http_port 3128

# ── Access control lists ─────────────────────────────────────────────────────

# Demo network (maps to rfc1918-10 + internal subnets in upstream squid rules)
acl demo_network src ${DEMO_NETWORK}

# RFC1918 ranges — upstream squid.yaml allows all rfc1918-10 (10.0.0.0/8)
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16

acl localhost src 127.0.0.1/32

# Allowed outbound ports — mirrors upstream squid.internal allowed ports:
#   ftp (tcp/21), http (tcp/80), https (tcp/443), matrix-federation (tcp/8448)
# Plus squid-to-squid (tcp/3128) and ssh (tcp/22) for operational access.
acl Safe_ports port 21      # ftp
acl Safe_ports port 80      # http
acl Safe_ports port 443     # https
acl Safe_ports port 3128    # squid
acl Safe_ports port 22      # ssh
acl Safe_ports port 8448    # matrix-federation
acl Safe_ports port 53      # dns

acl CONNECT method CONNECT

# ── Access rules ─────────────────────────────────────────────────────────────

# Deny requests to unsafe ports
http_access deny !Safe_ports

# Deny CONNECT to non-SSL ports
http_access deny CONNECT !Safe_ports

# Allow from demo network (mirrors upstream: rfc1918-10 allowed to squid.internal)
http_access allow demo_network
http_access allow localnet
http_access allow localhost

# Deny everything else (upstream default: deny all unmatched)
http_access deny all

# ── Logging ──────────────────────────────────────────────────────────────────

access_log /var/log/squid/access.log

# ── Cache ────────────────────────────────────────────────────────────────────

cache_dir ufs /var/spool/squid 100 16 256
cache_mem 64 MB

# ── DNS ──────────────────────────────────────────────────────────────────────

# Primary: demo DNS VM (mirrors upstream use of internal DNS)
# Fallback: Google public DNS
dns_nameservers ${DEMO_DNS_IP} 8.8.8.8

# ── Refresh patterns ─────────────────────────────────────────────────────────

refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
CONF
echo "Written: ${SQUID_OUT}"

echo ""
echo "=== sync-from-upstream complete ==="
echo ""
echo "Generated files:"
echo "  ${UFW_OUT}"
echo "  ${IPTABLES_OUT}"
echo "  ${SQUID_OUT}"
echo ""
echo "Upstream firewall rules inspected:"
echo "  rules/is/ps7.yaml     — PS7 prodstack firewall rules"
echo "  rules/is/testing.yaml — PS5/PS7 tunnel rules"
echo "  rules/is/squid.yaml   — squid.internal egress proxy access rules"
echo "  services/is/ps7.yaml  — PS7 host/subnet definitions"
echo "  defs/hosts.yaml       — ps7-egress-proxy IPs: 91.189.92.10/11/12"
echo "  defs/ports.yaml       — squid=tcp/3128, ssh=tcp/22, http=tcp/80, etc."
